# Generated by Django 5.1.5 on 2025-01-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projets/')),
                ('type', models.CharField(choices=[('cartographie', 'Cartographie'), ('livres', 'Livres'), ('genealogie', 'Généalogie'), ('autre', 'Autre')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lien', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
