# Generated by Django 5.1.5 on 2025-01-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projet',
            table='pages_projet',
        ),
    ]
