# Generated by Django 5.1.5 on 2025-01-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_projet_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='image_caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
