# Generated by Django 5.1.5 on 2025-01-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_projet_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='lien',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='type',
            field=models.CharField(choices=[('cartographie', '🗺️ Cartographie'), ('livres', 'Livres'), ('genealogie', '🌳 Généalogie'), ('autre', 'Autre')], max_length=20),
        ),
    ]
