# Generated by Django 5.1.5 on 2025-01-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_projet_lien_alter_projet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='epingle',
            field=models.BooleanField(default=False),
        ),
    ]
