# Generated by Django 5.1.6 on 2025-02-08 20:04

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiarras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoboxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infobox_type_name', models.CharField(max_length=10)),
                ('color_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.CreateModel(
            name='Infobox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('construction_date', models.DateField(blank=True, null=True)),
                ('demolition_date', models.DateField(blank=True, null=True)),
                ('architect', models.CharField(blank=True, max_length=255, null=True)),
                ('first_mention', models.CharField(blank=True, max_length=255, null=True)),
                ('infobox_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoboxes', to='wikiarras.page')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces_set', to='wikiarras.infobox')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by_set', to='wikiarras.infobox')),
                ('infobox_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiarras.infoboxtype')),
            ],
        ),
        migrations.CreateModel(
            name='PageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('char_diff', models.IntegerField(default=0)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='wikiarras.page')),
            ],
        ),
    ]
