# Generated by Django 5.1.5 on 2025-02-06 11:31

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiarras', '0002_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
