# Generated by Django 5.1.5 on 2025-02-06 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiarras', '0003_alter_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoboxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infobox_type_name', models.CharField(max_length=100)),
                ('color_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Infobox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('construction_date', models.DateField(blank=True, null=True)),
                ('demolition_date', models.DateField(blank=True, null=True)),
                ('architect', models.CharField(blank=True, max_length=255, null=True)),
                ('first_mention', models.CharField(blank=True, max_length=255, null=True)),
                ('infobox_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoboxes', to='wikiarras.page')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces_set', to='wikiarras.infobox')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by_set', to='wikiarras.infobox')),
                ('infobox_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiarras.infoboxtype')),
            ],
        ),
    ]
