# Generated by Django 5.1.5 on 2025-02-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiarras', '0004_infoboxtype_infobox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoboxtype',
            name='infobox_type_name',
            field=models.CharField(max_length=10),
        ),
    ]
