# Generated by Django 5.1.5 on 2025-02-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiarras', '0006_pagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagehistory',
            name='char_diff',
            field=models.IntegerField(default=0),
        ),
    ]
